function_documentation.Rmd:
  path: dev/function_documentation.Rmd
  state: active
  R:
  - R/add_duration.R
  - R/add_duration_from_audit.R
  - R/add_info_to_cleaning_log.R
  - R/add_percentage_missing.R
  - R/add_ridl.R
  - R/auto_detect_sm_parents.R
  - R/auto_sm_parent_child.R
  - R/check_duplicate.R
  - R/check_duration.R
  - R/check_fcs.R
  - R/check_logical.R
  - R/check_logical_with_list.R
  - R/check_others.R
  - R/check_others_checks.R
  - R/check_outliers.R
  - R/check_percentage_missing.R
  - R/check_pii.R
  - R/check_soft_duplicates.R
  - R/check_value.R
  - R/coerce_to_character.R
  - R/create_audit_list.R
  - R/create_clean_data.R
  - R/create_cleaning_log.R
  - R/create_col_range.R
  - R/create_combined_log.R
  - R/create_duration_from_audit_sum_all.R
  - R/create_duration_from_audit_with_start_end.R
  - R/create_formated_wb.R
  - R/create_formatted_choices.R
  - R/create_logic_for_other.R
  - R/create_validation_list.R
  - R/create_xlsx_cleaning_log.R
  - R/detect_uuid.R
  - R/detect_variable.R
  - R/knit_big_table.R
  - R/print_log.R
  - R/recreate_parent_column.R
  - R/review_cleaning.R
  - R/review_cleaning_log.R
  - R/review_others.R
  - R/review_sample_frame_with_dataset.R
  - R/verify_valid_choices.R
  - R/verify_valid_survey.R
  tests:
  - tests/testthat/test-add_percentage_missing.R
  - tests/testthat/test-add_duration.R
  - tests/testthat/test-add_info_to_cleaning_log.R
  - tests/testthat/test-add_duration_from_audit.R
  - tests/testthat/test-check_duration.R
  - tests/testthat/test-check_duplicate.R
  - tests/testthat/test-check_fcs.R
  - tests/testthat/test-check_logical.R
  - tests/testthat/test-check_logical_with_list.R
  - tests/testthat/test-check_others_checks.R
  - tests/testthat/test-check_others.R
  - tests/testthat/test-check_outliers.R
  - tests/testthat/test-check_percentage_missing.R
  - tests/testthat/test-check_pii.R
  - tests/testthat/test-check_soft_duplicates.R
  - tests/testthat/test-check_value.R
  - tests/testthat/test-create_audit_list.R
  - tests/testthat/test-create_duration_from_audit_with_start_end.R
  - tests/testthat/test-create_duration_from_audit_sum_all.R
  - tests/testthat/test-create_combined_log.R
  - tests/testthat/test-create_logic_for_other.R
  - tests/testthat/test-create_formated_wb.R
  - tests/testthat/test-create_cleaning_log.R
  - tests/testthat/test-create_xlsx_cleaning_log.R
  - tests/testthat/test-create_clean_data.R
  - tests/testthat/test-review_cleaning_log.R
  - tests/testthat/test-review_cleaning.R
  - tests/testthat/test-review_others.R
  - tests/testthat/test-review_sample_frame_with_dataset.R
  - tests/testthat/test-auto_detect_sm_parents.R
  - tests/testthat/test-auto_sm_parent_child.R
  - tests/testthat/test-recreate_parent_column.R
  - tests/testthat/test-detect_variable.R
  - tests/testthat/test-verify_valid_survey.R
  - tests/testthat/test-verify_valid_choices.R
  - tests/testthat/test-create_validation_list.R
  - tests/testthat/test-create_formatted_choices.R
  - tests/testthat/test-create_col_range.R
  - tests/testthat/test-coerce_to_character.R
  - tests/testthat/test-detect_uuid.R
  - tests/testthat/test-knit_big_table.R
  - tests/testthat/test-print_log.R
  - tests/testthat/test-add_ridl.R
  vignettes: vignettes/function_documentation.Rmd
  inflate:
    flat_file: dev/function_documentation.Rmd
    vignette_name: function_documentation
    open_vignette: true
    check: true
    document: true
    overwrite: ask
